package solutions

import "testing"

/*
------------------------------------------------------------------------------------------------
 author: Eltjon Metko        ::         Even Fibonacci numbers
------------------------------------------------------------------------------------------------
Problem URL : https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

------------------------------------------------------------------------------------------------
*/

func Euler002() int{
	max := 4000000
	a, b := 0, 1
	sum := 0
	for b < max {
		if b % 2 == 0 {
			sum += b
		}
		a, b = b, a + b
	}
	return sum
}

func TestEuler002(t *testing.T){
	expected := 4613732
	got := Euler002()
	t.Logf("Answer: %v | Expected %v",got, expected)
	if got!=expected{
		t.Fail()
	}
}

